---
- hosts: localhost
  gather_facts: yes

  pre_tasks:
      - name: Install Desktop
        yum:
            name: "{{ item }}"
            state: present
        become: yes
        with_items:
            - "@x11"
            - "@Xfce"
            - "@internet-browser"
      - name: Switch To Graphical Desktop
        command: systemctl isolate graphical.target
        become: yes
      - name: Make Graphical Desktop The Default
        command: systemctl set-default graphical.target
        become: yes

  roles:
      - kurron.logfaces
      - kurron.atlassian
      - kurron.aws
      - { role: kurron.docker-host, docker_engine_storage_driver: overlay }
      - kurron.hashicorp
      - kurron.javascript-developer
      - kurron.jvm-developer
      - { role: kurron.operations, operations_loggly_install: false, operations_datadog_install: false }
      - kurron.python-developer
      - kurron.software-developer
      - kurron.sql-developer

  post_tasks:
      - name: Clear Out Downloads
        shell: "rm -f {{ansible_user_dir}}/Downloads/*.*"
      - name: Clear Out Guest Additions
        shell: "rm -f {{ansible_user_dir}}/*.iso"
      - name: Erase downloaded archive files
        shell: "yum clean all"
